scraper:
  parallelism: 6
  selector: "article p, article h1, article h2, article h3, article h4, article h5, article h6"
job_loader:
  backpressure: 100
  page_cutoff: 3
word_bank_url: "https://raw.githubusercontent.com/dwyl/english-words/master/words.txt"
jobs_url:     "https://drive.usercontent.google.com/u/0/uc?id=1TF4RPuj8iFwpa-lyhxG67V8NDlktmTGi&export=download"
